version: '3.8'
services:
  fast_api:
    build: .
    image: fastapi-container
    env_file:
      - .env
    ports:
      - 8000:8000
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
